# Generated by Django 3.0.2 on 2020-01-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coent',
            new_name='Comment',
        ),
    ]
